CREATE TABLE IF NOT EXISTS workflow_action_outbox (
    id             BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    callSID        VARCHAR(128) DEFAULT NULL,
    workflowId     VARCHAR(100) NOT NULL,
    actionType     VARCHAR(100) NOT NULL,
    idempotencyKey VARCHAR(190) NOT NULL,
    payloadJson    JSON NOT NULL,
    payloadHash    CHAR(64) NOT NULL,
    resultJson     JSON DEFAULT NULL,
    status         ENUM('queued', 'processing', 'retry', 'completed', 'failed', 'dead_letter', 'cancelled') NOT NULL DEFAULT 'queued',
    attemptCount   INT UNSIGNED NOT NULL DEFAULT 0,
    maxAttempts    INT UNSIGNED NOT NULL DEFAULT 3,
    availableAt    DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    lockedAt       DATETIME(3) DEFAULT NULL,
    lockedBy       VARCHAR(100) DEFAULT NULL,
    lastError      VARCHAR(512) DEFAULT NULL,
    createdAt      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt      TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    completedAt    DATETIME(3) DEFAULT NULL,
    UNIQUE KEY uq_workflow_action_idempotency (idempotencyKey),
    INDEX idx_workflow_action_due (status, availableAt, id),
    INDEX idx_workflow_action_call (callSID, workflowId, actionType),
    INDEX idx_workflow_action_locked (lockedAt, lockedBy)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;