// utils/telemetry/schema.js

const EVENTS = Object.freeze({
  CALL_SESSION_START: "CALL_SESSION_START",
  USER_TRANSCRIPT: "USER_TRANSCRIPT",
  DEGRADATION_TRANSITION: "DEGRADATION_TRANSITION",
  UNLOCK_EVALUATION: "UNLOCK_EVALUATION",
  CLARIFICATION_TRIGGERED: "CLARIFICATION_TRIGGERED",
  INTERACTION_MODE_CHANGE: "INTERACTION_MODE_CHANGE",
  LATENCY_METRIC: "LATENCY_METRIC",
  MEMORY_SNAPSHOT: "MEMORY_SNAPSHOT",
  GHOST_EMISSION_BLOCKED: "GHOST_EMISSION_BLOCKED",
  CALL_SESSION_END: "CALL_SESSION_END",

  // Forward-safe additions (non-breaking)
  SILENCE_TIMEOUT_TRIGGERED: "SILENCE_TIMEOUT_TRIGGERED",
  TELEMETRY_BUFFER_OVERFLOW: "TELEMETRY_BUFFER_OVERFLOW"
});

module.exports = Object.freeze({
  EVENTS
});